#Direct cmake to use this file by passing -DCMAKE_TOOLCHAIN_FILE=/path/to/file
SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_SYSROOT /home/abigagli/SYSROOTS/fedora)
SET(CMAKE_STAGING_PREFIX /tmp/STAGING)

#SET(CMAKE_C_COMPILER gcc)
#SET(CMAKE_CXX_COMPILER g++)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
